
spring:
  salmon:
    scan: com.data2.example
    database:
      jdbc:
        url: jdbc:mysql://talkmovie.cn:7762/talkmovie?characterEncoding=UTF-8
        username: root
        password: $ZEROone123
      partition:
        url: jdbc:mysql://XXX:7762/talkmovie?characterEncoding=UTF-8
        username: root
        password: $ZEROone123
        mapping: db0:talkmovie.cn,db1:talkmovie.cn
        table: hash(tm_article_info, articleID, 0, 2, 2)
